// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.12.4
// source: rng.proto

package bggrngpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	BGGRng_GetRngs_FullMethodName = "/bggrngpb.BGGRng/getRngs"
)

// BGGRngClient is the client API for BGGRng service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BGGRngClient interface {
	// getRngs - get rngs
	GetRngs(ctx context.Context, in *RequestRngs, opts ...grpc.CallOption) (*ReplyRngs, error)
}

type bGGRngClient struct {
	cc grpc.ClientConnInterface
}

func NewBGGRngClient(cc grpc.ClientConnInterface) BGGRngClient {
	return &bGGRngClient{cc}
}

func (c *bGGRngClient) GetRngs(ctx context.Context, in *RequestRngs, opts ...grpc.CallOption) (*ReplyRngs, error) {
	out := new(ReplyRngs)
	err := c.cc.Invoke(ctx, BGGRng_GetRngs_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BGGRngServer is the server API for BGGRng service.
// All implementations must embed UnimplementedBGGRngServer
// for forward compatibility
type BGGRngServer interface {
	// getRngs - get rngs
	GetRngs(context.Context, *RequestRngs) (*ReplyRngs, error)
	mustEmbedUnimplementedBGGRngServer()
}

// UnimplementedBGGRngServer must be embedded to have forward compatible implementations.
type UnimplementedBGGRngServer struct {
}

func (UnimplementedBGGRngServer) GetRngs(context.Context, *RequestRngs) (*ReplyRngs, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRngs not implemented")
}
func (UnimplementedBGGRngServer) mustEmbedUnimplementedBGGRngServer() {}

// UnsafeBGGRngServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BGGRngServer will
// result in compilation errors.
type UnsafeBGGRngServer interface {
	mustEmbedUnimplementedBGGRngServer()
}

func RegisterBGGRngServer(s grpc.ServiceRegistrar, srv BGGRngServer) {
	s.RegisterService(&BGGRng_ServiceDesc, srv)
}

func _BGGRng_GetRngs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestRngs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BGGRngServer).GetRngs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BGGRng_GetRngs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BGGRngServer).GetRngs(ctx, req.(*RequestRngs))
	}
	return interceptor(ctx, in, info, handler)
}

// BGGRng_ServiceDesc is the grpc.ServiceDesc for BGGRng service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BGGRng_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bggrngpb.BGGRng",
	HandlerType: (*BGGRngServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getRngs",
			Handler:    _BGGRng_GetRngs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rng.proto",
}
