// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: dtgame.proto

package sgc7pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DTGameLogicClient is the client API for DTGameLogic service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DTGameLogicClient interface {
	// getConfig - get config
	GetConfig(ctx context.Context, in *RequestConfig, opts ...grpc.CallOption) (*GameConfig, error)
	// initialize - initialize a player
	Initialize(ctx context.Context, in *RequestInitialize, opts ...grpc.CallOption) (*PlayerState, error)
	// play - play game
	Play(ctx context.Context, in *RequestPlay, opts ...grpc.CallOption) (DTGameLogic_PlayClient, error)
}

type dTGameLogicClient struct {
	cc grpc.ClientConnInterface
}

func NewDTGameLogicClient(cc grpc.ClientConnInterface) DTGameLogicClient {
	return &dTGameLogicClient{cc}
}

func (c *dTGameLogicClient) GetConfig(ctx context.Context, in *RequestConfig, opts ...grpc.CallOption) (*GameConfig, error) {
	out := new(GameConfig)
	err := c.cc.Invoke(ctx, "/sgc7pb.DTGameLogic/getConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dTGameLogicClient) Initialize(ctx context.Context, in *RequestInitialize, opts ...grpc.CallOption) (*PlayerState, error) {
	out := new(PlayerState)
	err := c.cc.Invoke(ctx, "/sgc7pb.DTGameLogic/initialize", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dTGameLogicClient) Play(ctx context.Context, in *RequestPlay, opts ...grpc.CallOption) (DTGameLogic_PlayClient, error) {
	stream, err := c.cc.NewStream(ctx, &DTGameLogic_ServiceDesc.Streams[0], "/sgc7pb.DTGameLogic/play", opts...)
	if err != nil {
		return nil, err
	}
	x := &dTGameLogicPlayClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DTGameLogic_PlayClient interface {
	Recv() (*ReplyPlay, error)
	grpc.ClientStream
}

type dTGameLogicPlayClient struct {
	grpc.ClientStream
}

func (x *dTGameLogicPlayClient) Recv() (*ReplyPlay, error) {
	m := new(ReplyPlay)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DTGameLogicServer is the server API for DTGameLogic service.
// All implementations must embed UnimplementedDTGameLogicServer
// for forward compatibility
type DTGameLogicServer interface {
	// getConfig - get config
	GetConfig(context.Context, *RequestConfig) (*GameConfig, error)
	// initialize - initialize a player
	Initialize(context.Context, *RequestInitialize) (*PlayerState, error)
	// play - play game
	Play(*RequestPlay, DTGameLogic_PlayServer) error
	mustEmbedUnimplementedDTGameLogicServer()
}

// UnimplementedDTGameLogicServer must be embedded to have forward compatible implementations.
type UnimplementedDTGameLogicServer struct {
}

func (UnimplementedDTGameLogicServer) GetConfig(context.Context, *RequestConfig) (*GameConfig, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConfig not implemented")
}
func (UnimplementedDTGameLogicServer) Initialize(context.Context, *RequestInitialize) (*PlayerState, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Initialize not implemented")
}
func (UnimplementedDTGameLogicServer) Play(*RequestPlay, DTGameLogic_PlayServer) error {
	return status.Errorf(codes.Unimplemented, "method Play not implemented")
}
func (UnimplementedDTGameLogicServer) mustEmbedUnimplementedDTGameLogicServer() {}

// UnsafeDTGameLogicServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DTGameLogicServer will
// result in compilation errors.
type UnsafeDTGameLogicServer interface {
	mustEmbedUnimplementedDTGameLogicServer()
}

func RegisterDTGameLogicServer(s grpc.ServiceRegistrar, srv DTGameLogicServer) {
	s.RegisterService(&DTGameLogic_ServiceDesc, srv)
}

func _DTGameLogic_GetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestConfig)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DTGameLogicServer).GetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sgc7pb.DTGameLogic/getConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DTGameLogicServer).GetConfig(ctx, req.(*RequestConfig))
	}
	return interceptor(ctx, in, info, handler)
}

func _DTGameLogic_Initialize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestInitialize)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DTGameLogicServer).Initialize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sgc7pb.DTGameLogic/initialize",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DTGameLogicServer).Initialize(ctx, req.(*RequestInitialize))
	}
	return interceptor(ctx, in, info, handler)
}

func _DTGameLogic_Play_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RequestPlay)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DTGameLogicServer).Play(m, &dTGameLogicPlayServer{stream})
}

type DTGameLogic_PlayServer interface {
	Send(*ReplyPlay) error
	grpc.ServerStream
}

type dTGameLogicPlayServer struct {
	grpc.ServerStream
}

func (x *dTGameLogicPlayServer) Send(m *ReplyPlay) error {
	return x.ServerStream.SendMsg(m)
}

// DTGameLogic_ServiceDesc is the grpc.ServiceDesc for DTGameLogic service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DTGameLogic_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sgc7pb.DTGameLogic",
	HandlerType: (*DTGameLogicServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getConfig",
			Handler:    _DTGameLogic_GetConfig_Handler,
		},
		{
			MethodName: "initialize",
			Handler:    _DTGameLogic_Initialize_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "play",
			Handler:       _DTGameLogic_Play_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "dtgame.proto",
}
