// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.21.12
// source: gamecollection.proto

package sgc7pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RequestInitGame - initial game
type RequestInitGame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameCode      string                 `protobuf:"bytes,1,opt,name=gameCode,proto3" json:"gameCode,omitempty"`
	Config        string                 `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestInitGame) Reset() {
	*x = RequestInitGame{}
	mi := &file_gamecollection_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestInitGame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestInitGame) ProtoMessage() {}

func (x *RequestInitGame) ProtoReflect() protoreflect.Message {
	mi := &file_gamecollection_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestInitGame.ProtoReflect.Descriptor instead.
func (*RequestInitGame) Descriptor() ([]byte, []int) {
	return file_gamecollection_proto_rawDescGZIP(), []int{0}
}

func (x *RequestInitGame) GetGameCode() string {
	if x != nil {
		return x.GameCode
	}
	return ""
}

func (x *RequestInitGame) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

// ReplyInitGame - reply initial game
type ReplyInitGame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsOK          bool                   `protobuf:"varint,1,opt,name=isOK,proto3" json:"isOK,omitempty"`
	Err           string                 `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplyInitGame) Reset() {
	*x = ReplyInitGame{}
	mi := &file_gamecollection_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyInitGame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyInitGame) ProtoMessage() {}

func (x *ReplyInitGame) ProtoReflect() protoreflect.Message {
	mi := &file_gamecollection_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyInitGame.ProtoReflect.Descriptor instead.
func (*ReplyInitGame) Descriptor() ([]byte, []int) {
	return file_gamecollection_proto_rawDescGZIP(), []int{1}
}

func (x *ReplyInitGame) GetIsOK() bool {
	if x != nil {
		return x.IsOK
	}
	return false
}

func (x *ReplyInitGame) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

// RequestGameConfig - get game config
type RequestGameConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameCode      string                 `protobuf:"bytes,1,opt,name=gameCode,proto3" json:"gameCode,omitempty"`
	Req           *RequestConfig         `protobuf:"bytes,2,opt,name=req,proto3" json:"req,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestGameConfig) Reset() {
	*x = RequestGameConfig{}
	mi := &file_gamecollection_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestGameConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestGameConfig) ProtoMessage() {}

func (x *RequestGameConfig) ProtoReflect() protoreflect.Message {
	mi := &file_gamecollection_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestGameConfig.ProtoReflect.Descriptor instead.
func (*RequestGameConfig) Descriptor() ([]byte, []int) {
	return file_gamecollection_proto_rawDescGZIP(), []int{2}
}

func (x *RequestGameConfig) GetGameCode() string {
	if x != nil {
		return x.GameCode
	}
	return ""
}

func (x *RequestGameConfig) GetReq() *RequestConfig {
	if x != nil {
		return x.Req
	}
	return nil
}

// ReplyGameConfig - reply game config
type ReplyGameConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsOK          bool                   `protobuf:"varint,1,opt,name=isOK,proto3" json:"isOK,omitempty"`
	Err           string                 `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	GameConfig    *GameConfig            `protobuf:"bytes,3,opt,name=gameConfig,proto3" json:"gameConfig,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplyGameConfig) Reset() {
	*x = ReplyGameConfig{}
	mi := &file_gamecollection_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyGameConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyGameConfig) ProtoMessage() {}

func (x *ReplyGameConfig) ProtoReflect() protoreflect.Message {
	mi := &file_gamecollection_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyGameConfig.ProtoReflect.Descriptor instead.
func (*ReplyGameConfig) Descriptor() ([]byte, []int) {
	return file_gamecollection_proto_rawDescGZIP(), []int{3}
}

func (x *ReplyGameConfig) GetIsOK() bool {
	if x != nil {
		return x.IsOK
	}
	return false
}

func (x *ReplyGameConfig) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

func (x *ReplyGameConfig) GetGameConfig() *GameConfig {
	if x != nil {
		return x.GameConfig
	}
	return nil
}

// RequestInitializeGamePlayer - initialize a game player
type RequestInitializeGamePlayer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameCode      string                 `protobuf:"bytes,1,opt,name=gameCode,proto3" json:"gameCode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestInitializeGamePlayer) Reset() {
	*x = RequestInitializeGamePlayer{}
	mi := &file_gamecollection_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestInitializeGamePlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestInitializeGamePlayer) ProtoMessage() {}

func (x *RequestInitializeGamePlayer) ProtoReflect() protoreflect.Message {
	mi := &file_gamecollection_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestInitializeGamePlayer.ProtoReflect.Descriptor instead.
func (*RequestInitializeGamePlayer) Descriptor() ([]byte, []int) {
	return file_gamecollection_proto_rawDescGZIP(), []int{4}
}

func (x *RequestInitializeGamePlayer) GetGameCode() string {
	if x != nil {
		return x.GameCode
	}
	return ""
}

// ReplyInitializeGamePlayer - reply initialize a game player
type ReplyInitializeGamePlayer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsOK          bool                   `protobuf:"varint,1,opt,name=isOK,proto3" json:"isOK,omitempty"`
	Err           string                 `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	PlayerState   *PlayerState           `protobuf:"bytes,3,opt,name=playerState,proto3" json:"playerState,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplyInitializeGamePlayer) Reset() {
	*x = ReplyInitializeGamePlayer{}
	mi := &file_gamecollection_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyInitializeGamePlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyInitializeGamePlayer) ProtoMessage() {}

func (x *ReplyInitializeGamePlayer) ProtoReflect() protoreflect.Message {
	mi := &file_gamecollection_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyInitializeGamePlayer.ProtoReflect.Descriptor instead.
func (*ReplyInitializeGamePlayer) Descriptor() ([]byte, []int) {
	return file_gamecollection_proto_rawDescGZIP(), []int{5}
}

func (x *ReplyInitializeGamePlayer) GetIsOK() bool {
	if x != nil {
		return x.IsOK
	}
	return false
}

func (x *ReplyInitializeGamePlayer) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

func (x *ReplyInitializeGamePlayer) GetPlayerState() *PlayerState {
	if x != nil {
		return x.PlayerState
	}
	return nil
}

// RequestPlayGame - play input parameters for the game
type RequestPlayGame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameCode      string                 `protobuf:"bytes,1,opt,name=gameCode,proto3" json:"gameCode,omitempty"`
	Play          *RequestPlay           `protobuf:"bytes,2,opt,name=play,proto3" json:"play,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestPlayGame) Reset() {
	*x = RequestPlayGame{}
	mi := &file_gamecollection_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestPlayGame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestPlayGame) ProtoMessage() {}

func (x *RequestPlayGame) ProtoReflect() protoreflect.Message {
	mi := &file_gamecollection_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestPlayGame.ProtoReflect.Descriptor instead.
func (*RequestPlayGame) Descriptor() ([]byte, []int) {
	return file_gamecollection_proto_rawDescGZIP(), []int{6}
}

func (x *RequestPlayGame) GetGameCode() string {
	if x != nil {
		return x.GameCode
	}
	return ""
}

func (x *RequestPlayGame) GetPlay() *RequestPlay {
	if x != nil {
		return x.Play
	}
	return nil
}

// RequestPlayGame - play input parameters for the game
type ReplyPlayGame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsOK          bool                   `protobuf:"varint,1,opt,name=isOK,proto3" json:"isOK,omitempty"`
	Err           string                 `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	Play          *ReplyPlay             `protobuf:"bytes,3,opt,name=play,proto3" json:"play,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplyPlayGame) Reset() {
	*x = ReplyPlayGame{}
	mi := &file_gamecollection_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyPlayGame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyPlayGame) ProtoMessage() {}

func (x *ReplyPlayGame) ProtoReflect() protoreflect.Message {
	mi := &file_gamecollection_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyPlayGame.ProtoReflect.Descriptor instead.
func (*ReplyPlayGame) Descriptor() ([]byte, []int) {
	return file_gamecollection_proto_rawDescGZIP(), []int{7}
}

func (x *ReplyPlayGame) GetIsOK() bool {
	if x != nil {
		return x.IsOK
	}
	return false
}

func (x *ReplyPlayGame) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

func (x *ReplyPlayGame) GetPlay() *ReplyPlay {
	if x != nil {
		return x.Play
	}
	return nil
}

var File_gamecollection_proto protoreflect.FileDescriptor

var file_gamecollection_proto_rawDesc = string([]byte{
	0x0a, 0x14, 0x67, 0x61, 0x6d, 0x65, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x73, 0x67, 0x63, 0x37, 0x70, 0x62, 0x1a, 0x0a,
	0x67, 0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x45, 0x0a, 0x0f, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x6e, 0x69, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x67, 0x61, 0x6d, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x67, 0x61, 0x6d, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x22, 0x35, 0x0a, 0x0d, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x49, 0x6e, 0x69, 0x74, 0x47, 0x61,
	0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x73, 0x4f, 0x4b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x04, 0x69, 0x73, 0x4f, 0x4b, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x65, 0x72, 0x72, 0x22, 0x58, 0x0a, 0x11, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x1a, 0x0a,
	0x08, 0x67, 0x61, 0x6d, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x67, 0x61, 0x6d, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x27, 0x0a, 0x03, 0x72, 0x65, 0x71,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x73, 0x67, 0x63, 0x37, 0x70, 0x62, 0x2e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x03, 0x72,
	0x65, 0x71, 0x22, 0x6b, 0x0a, 0x0f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x47, 0x61, 0x6d, 0x65, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x73, 0x4f, 0x4b, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x04, 0x69, 0x73, 0x4f, 0x4b, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x72, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x65, 0x72, 0x72, 0x12, 0x32, 0x0a, 0x0a, 0x67,
	0x61, 0x6d, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x12, 0x2e, 0x73, 0x67, 0x63, 0x37, 0x70, 0x62, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x52, 0x0a, 0x67, 0x61, 0x6d, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x22,
	0x39, 0x0a, 0x1b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61,
	0x6c, 0x69, 0x7a, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x1a,
	0x0a, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x78, 0x0a, 0x19, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x47, 0x61, 0x6d,
	0x65, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x73, 0x4f, 0x4b, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x69, 0x73, 0x4f, 0x4b, 0x12, 0x10, 0x0a, 0x03, 0x65,
	0x72, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x65, 0x72, 0x72, 0x12, 0x35, 0x0a,
	0x0b, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x13, 0x2e, 0x73, 0x67, 0x63, 0x37, 0x70, 0x62, 0x2e, 0x50, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x0b, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x22, 0x56, 0x0a, 0x0f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50,
	0x6c, 0x61, 0x79, 0x47, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x43,
	0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x43,
	0x6f, 0x64, 0x65, 0x12, 0x27, 0x0a, 0x04, 0x70, 0x6c, 0x61, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x13, 0x2e, 0x73, 0x67, 0x63, 0x37, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x52, 0x04, 0x70, 0x6c, 0x61, 0x79, 0x22, 0x5c, 0x0a, 0x0d,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x50, 0x6c, 0x61, 0x79, 0x47, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x69, 0x73, 0x4f, 0x4b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x69, 0x73, 0x4f,
	0x4b, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x65, 0x72, 0x72, 0x12, 0x25, 0x0a, 0x04, 0x70, 0x6c, 0x61, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x11, 0x2e, 0x73, 0x67, 0x63, 0x37, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x50, 0x6c, 0x61, 0x79, 0x52, 0x04, 0x70, 0x6c, 0x61, 0x79, 0x32, 0xfb, 0x02, 0x0a, 0x13, 0x47,
	0x61, 0x6d, 0x65, 0x4c, 0x6f, 0x67, 0x69, 0x63, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x3c, 0x0a, 0x08, 0x69, 0x6e, 0x69, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x12, 0x17,
	0x2e, 0x73, 0x67, 0x63, 0x37, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49,
	0x6e, 0x69, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x1a, 0x15, 0x2e, 0x73, 0x67, 0x63, 0x37, 0x70, 0x62,
	0x2e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x49, 0x6e, 0x69, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x22, 0x00,
	0x12, 0x45, 0x0a, 0x0d, 0x67, 0x65, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x12, 0x19, 0x2e, 0x73, 0x67, 0x63, 0x37, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x1a, 0x17, 0x2e, 0x73,
	0x67, 0x63, 0x37, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x47, 0x61, 0x6d, 0x65, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x22, 0x00, 0x12, 0x60, 0x0a, 0x14, 0x69, 0x6e, 0x69, 0x74, 0x69,
	0x61, 0x6c, 0x69, 0x7a, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12,
	0x23, 0x2e, 0x73, 0x67, 0x63, 0x37, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x50, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x1a, 0x21, 0x2e, 0x73, 0x67, 0x63, 0x37, 0x70, 0x62, 0x2e, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x47, 0x61, 0x6d,
	0x65, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x22, 0x00, 0x12, 0x3e, 0x0a, 0x08, 0x70, 0x6c, 0x61,
	0x79, 0x47, 0x61, 0x6d, 0x65, 0x12, 0x17, 0x2e, 0x73, 0x67, 0x63, 0x37, 0x70, 0x62, 0x2e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x47, 0x61, 0x6d, 0x65, 0x1a, 0x15,
	0x2e, 0x73, 0x67, 0x63, 0x37, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x50, 0x6c, 0x61,
	0x79, 0x47, 0x61, 0x6d, 0x65, 0x22, 0x00, 0x30, 0x01, 0x12, 0x3d, 0x0a, 0x09, 0x70, 0x6c, 0x61,
	0x79, 0x47, 0x61, 0x6d, 0x65, 0x32, 0x12, 0x17, 0x2e, 0x73, 0x67, 0x63, 0x37, 0x70, 0x62, 0x2e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x47, 0x61, 0x6d, 0x65, 0x1a,
	0x15, 0x2e, 0x73, 0x67, 0x63, 0x37, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x50, 0x6c,
	0x61, 0x79, 0x47, 0x61, 0x6d, 0x65, 0x22, 0x00, 0x42, 0x29, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x7a, 0x68, 0x73, 0x30, 0x30, 0x37, 0x2f, 0x73, 0x6c,
	0x6f, 0x74, 0x73, 0x67, 0x61, 0x6d, 0x65, 0x63, 0x6f, 0x72, 0x65, 0x37, 0x2f, 0x73, 0x67, 0x63,
	0x37, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_gamecollection_proto_rawDescOnce sync.Once
	file_gamecollection_proto_rawDescData []byte
)

func file_gamecollection_proto_rawDescGZIP() []byte {
	file_gamecollection_proto_rawDescOnce.Do(func() {
		file_gamecollection_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gamecollection_proto_rawDesc), len(file_gamecollection_proto_rawDesc)))
	})
	return file_gamecollection_proto_rawDescData
}

var file_gamecollection_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_gamecollection_proto_goTypes = []any{
	(*RequestInitGame)(nil),             // 0: sgc7pb.RequestInitGame
	(*ReplyInitGame)(nil),               // 1: sgc7pb.ReplyInitGame
	(*RequestGameConfig)(nil),           // 2: sgc7pb.RequestGameConfig
	(*ReplyGameConfig)(nil),             // 3: sgc7pb.ReplyGameConfig
	(*RequestInitializeGamePlayer)(nil), // 4: sgc7pb.RequestInitializeGamePlayer
	(*ReplyInitializeGamePlayer)(nil),   // 5: sgc7pb.ReplyInitializeGamePlayer
	(*RequestPlayGame)(nil),             // 6: sgc7pb.RequestPlayGame
	(*ReplyPlayGame)(nil),               // 7: sgc7pb.ReplyPlayGame
	(*RequestConfig)(nil),               // 8: sgc7pb.RequestConfig
	(*GameConfig)(nil),                  // 9: sgc7pb.GameConfig
	(*PlayerState)(nil),                 // 10: sgc7pb.PlayerState
	(*RequestPlay)(nil),                 // 11: sgc7pb.RequestPlay
	(*ReplyPlay)(nil),                   // 12: sgc7pb.ReplyPlay
}
var file_gamecollection_proto_depIdxs = []int32{
	8,  // 0: sgc7pb.RequestGameConfig.req:type_name -> sgc7pb.RequestConfig
	9,  // 1: sgc7pb.ReplyGameConfig.gameConfig:type_name -> sgc7pb.GameConfig
	10, // 2: sgc7pb.ReplyInitializeGamePlayer.playerState:type_name -> sgc7pb.PlayerState
	11, // 3: sgc7pb.RequestPlayGame.play:type_name -> sgc7pb.RequestPlay
	12, // 4: sgc7pb.ReplyPlayGame.play:type_name -> sgc7pb.ReplyPlay
	0,  // 5: sgc7pb.GameLogicCollection.initGame:input_type -> sgc7pb.RequestInitGame
	2,  // 6: sgc7pb.GameLogicCollection.getGameConfig:input_type -> sgc7pb.RequestGameConfig
	4,  // 7: sgc7pb.GameLogicCollection.initializeGamePlayer:input_type -> sgc7pb.RequestInitializeGamePlayer
	6,  // 8: sgc7pb.GameLogicCollection.playGame:input_type -> sgc7pb.RequestPlayGame
	6,  // 9: sgc7pb.GameLogicCollection.playGame2:input_type -> sgc7pb.RequestPlayGame
	1,  // 10: sgc7pb.GameLogicCollection.initGame:output_type -> sgc7pb.ReplyInitGame
	3,  // 11: sgc7pb.GameLogicCollection.getGameConfig:output_type -> sgc7pb.ReplyGameConfig
	5,  // 12: sgc7pb.GameLogicCollection.initializeGamePlayer:output_type -> sgc7pb.ReplyInitializeGamePlayer
	7,  // 13: sgc7pb.GameLogicCollection.playGame:output_type -> sgc7pb.ReplyPlayGame
	7,  // 14: sgc7pb.GameLogicCollection.playGame2:output_type -> sgc7pb.ReplyPlayGame
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_gamecollection_proto_init() }
func file_gamecollection_proto_init() {
	if File_gamecollection_proto != nil {
		return
	}
	file_game_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gamecollection_proto_rawDesc), len(file_gamecollection_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gamecollection_proto_goTypes,
		DependencyIndexes: file_gamecollection_proto_depIdxs,
		MessageInfos:      file_gamecollection_proto_msgTypes,
	}.Build()
	File_gamecollection_proto = out.File
	file_gamecollection_proto_goTypes = nil
	file_gamecollection_proto_depIdxs = nil
}
