// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.12.4
// source: gamecollection.proto

package sgc7pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	GameLogicCollection_InitGame_FullMethodName = "/sgc7pb.GameLogicCollection/initGame"
)

// GameLogicCollectionClient is the client API for GameLogicCollection service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GameLogicCollectionClient interface {
	// initGame - initial game
	InitGame(ctx context.Context, in *RequestInitGame, opts ...grpc.CallOption) (*ReplyInitGame, error)
}

type gameLogicCollectionClient struct {
	cc grpc.ClientConnInterface
}

func NewGameLogicCollectionClient(cc grpc.ClientConnInterface) GameLogicCollectionClient {
	return &gameLogicCollectionClient{cc}
}

func (c *gameLogicCollectionClient) InitGame(ctx context.Context, in *RequestInitGame, opts ...grpc.CallOption) (*ReplyInitGame, error) {
	out := new(ReplyInitGame)
	err := c.cc.Invoke(ctx, GameLogicCollection_InitGame_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GameLogicCollectionServer is the server API for GameLogicCollection service.
// All implementations must embed UnimplementedGameLogicCollectionServer
// for forward compatibility
type GameLogicCollectionServer interface {
	// initGame - initial game
	InitGame(context.Context, *RequestInitGame) (*ReplyInitGame, error)
	mustEmbedUnimplementedGameLogicCollectionServer()
}

// UnimplementedGameLogicCollectionServer must be embedded to have forward compatible implementations.
type UnimplementedGameLogicCollectionServer struct {
}

func (UnimplementedGameLogicCollectionServer) InitGame(context.Context, *RequestInitGame) (*ReplyInitGame, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitGame not implemented")
}
func (UnimplementedGameLogicCollectionServer) mustEmbedUnimplementedGameLogicCollectionServer() {}

// UnsafeGameLogicCollectionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GameLogicCollectionServer will
// result in compilation errors.
type UnsafeGameLogicCollectionServer interface {
	mustEmbedUnimplementedGameLogicCollectionServer()
}

func RegisterGameLogicCollectionServer(s grpc.ServiceRegistrar, srv GameLogicCollectionServer) {
	s.RegisterService(&GameLogicCollection_ServiceDesc, srv)
}

func _GameLogicCollection_InitGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestInitGame)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameLogicCollectionServer).InitGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameLogicCollection_InitGame_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameLogicCollectionServer).InitGame(ctx, req.(*RequestInitGame))
	}
	return interceptor(ctx, in, info, handler)
}

// GameLogicCollection_ServiceDesc is the grpc.ServiceDesc for GameLogicCollection service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GameLogicCollection_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sgc7pb.GameLogicCollection",
	HandlerType: (*GameLogicCollectionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "initGame",
			Handler:    _GameLogicCollection_InitGame_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gamecollection.proto",
}
