// Code generated by MockGen. DO NOT EDIT.
// Source: ./utils/time.go

// Package sgc7utils is a generated GoMock package.
package sgc7utils

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
	time "time"
)

// MockTimeI is a mock of TimeI interface
type MockTimeI struct {
	ctrl     *gomock.Controller
	recorder *MockTimeIMockRecorder
}

// MockTimeIMockRecorder is the mock recorder for MockTimeI
type MockTimeIMockRecorder struct {
	mock *MockTimeI
}

// NewMockTimeI creates a new mock instance
func NewMockTimeI(ctrl *gomock.Controller) *MockTimeI {
	mock := &MockTimeI{ctrl: ctrl}
	mock.recorder = &MockTimeIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockTimeI) EXPECT() *MockTimeIMockRecorder {
	return m.recorder
}

// Now mocks base method
func (m *MockTimeI) Now() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Now")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// Now indicates an expected call of Now
func (mr *MockTimeIMockRecorder) Now() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Now", reflect.TypeOf((*MockTimeI)(nil).Now))
}
