name: Go

on:
  push:
    branches: [ master, v0.13 ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Go 1.22
      uses: actions/setup-go@v5
      with:
        go-version: '1.22.x'
        cache: true
      id: go

    - name: Download dependencies
      run: go mod download

    - name: Build
      run: go build ./...

    - name: Test
      run: go test -race -v -cover -coverprofile=coverage.out ./...
